export const MODIFY_YEAR = "MODIFY_YEAR";
export const MODIFY_BRANCH = "MODIFY_BRANCH";
export const MODIFY_SEM = "MODIFY_SEM";
export const MODIFY_AVGSUBGPA = "MODIFY_AVGSUBGPA";
export const MODIFY_AVGLABGPA = "MODIFY_AVGLABGPA";
